# Generated by Django 4.0.6 on 2022-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='language',
            field=models.CharField(default='ru', max_length=10),
            preserve_default=False,
        ),
    ]
