# Generated by Django 4.0.6 on 2022-07-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bid_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(default='alive', max_length=50),
        ),
        migrations.AlterField(
            model_name='bid',
            name='source',
            field=models.IntegerField(),
        ),
    ]
