# Generated by Django 4.0.6 on 2022-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
